import React from "react";
import { TabsContent } from "../ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Separator } from "../ui/separator";

function LicenseTerms() {
  return (
    <TabsContent value="license-terms">
      <Card className="shadow-lg max-w-4xl mx-auto bg-transparent border-0">
        <CardHeader>
          <CardTitle className="text-3xl font-bold ">
            Amaanah Software License Terms of Use
          </CardTitle>
          <p className="text-muted-foreground text-sm">Amaanah © 2025</p>
        </CardHeader>
        <CardContent className="space-y-6 text-muted-foreground text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold mb-2">Definitions</h2>
            <p className="leading-7">
              The Terms: This agreement.
            </p>
            <p className="leading-7">
              The Merchant: You, the merchant client of Amaanah services.
            </p>
            <p className="leading-7">
              We, Us, Our and like terms: Refers to Amaanah.
            </p>
            <p className="leading-7">
              You, Your, and like terms: Refers to the Merchant.
            </p>
            <p className="leading-7">
              The Parties: Amaanah and the Merchant.
            </p>
            <p className="leading-7">
              Subscribers: The Merchant and their staff members with access to the Merchant’s Amaanah
              account.
            </p>
            <p className="leading-7">
              Customers: The customers of the merchant using Amaanah services.
            </p>
            <p className="leading-7">
              Users: Anyone who encounters the Services, whether they are the Merchant, Subscribers, or
              Customers.
            </p>
            <p className="leading-7">
              The License Contract: The ordering document between Amaanah and the Merchant, upon
              which the Merchant agrees to obtain the Services.
            </p>
            <p className="leading-7">
              The Agreements: Collectively refers to the License Contract, Terms, the Privacy Policy, and any
              other agreements between the Parties regarding the sale and use of the Services.
            </p>
            <p className="leading-7">
              The Sites: Any web pages under the Amaanah brand.
            </p>
            <p className="leading-7">
              The Services: The Amaanah software, hardware, related services, and add-ons, including
              supported integrations with third-party affiliates or any other current or future services offered
              by Amaanah.
            </p>
            <p className="leading-7">
              The Content: All information, content, data, logos, marks, interfaces, designs, graphics,
              pictures, sound files, other files, and their selection and arrangement, provided by Amaanah.
            </p>
            <p className="leading-7">
              Merchant Content: Information provided by the Merchant to Amaanah, including content
              generated by the Merchant’s use of the Services.
            </p>
            <p className="leading-7">
              User Content: Information provided by Customers to Amaanah during their use or purchase of
              the Merchant’s products and services.
            </p>
            <p className="leading-7">
              Effective Date: The earlier of the Go-Live Date or the First Payment Date.
            </p>
            <p className="leading-7">
              Live Date: The date upon which the Merchant commences their use of the Services in their
              business environment.
            </p>
            <p className="leading-7">
              First Payment Date: The date specified as the First Payment Date in the Merchant’s License
              Contract.
            </p>
            <p className="leading-7">
              Agreement Created Date: The date specified as the Agreement Created Date in the Merchant’s
              License Contract.
            </p>
            <p className="leading-7">
              Social Media Areas: Collectively refers to any discussion forums, establishment information,
              bulletin boards, review services, or other forums in which the Merchant or third parties may
              post reviews, messages, materials, or other items.
            </p>
            <p className="leading-7">
              Confidential Information: Any information previously, now, or hereafter disclosed to a receiving
              party in connection with the parties’ business dealings with each other, of which the
              information is of a proprietary or otherwise sensitive nature and is not generally known.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Nature of the Terms</h2>
            <p className="leading-7">
              Amaanah provides the Amaanah point of sales software for hospitality, hardware, and
              the related Sites and Services to the Merchant subject to these terms of use. The Terms
              apply to the use of the Services and Content by all Merchants and Subscribers,
              including any additional products and services provided or referred by Us or third
              parties in conjunction with Amaanah Services. By accessing or using the Services,
              Merchants and their staff agree to be bound by the Terms legally.
            </p>
            <h3 className="text-lg font-semibold mt-4">i) Modification</h3>
            <p className="leading-7">
              Please note that Amaanah reserves the right to change or update the terms at any time,
              provided that the Merchant is given 30 days' notice. If the Merchant is not in agreement
              with such modifications, they may cancel their subscription to the Services by providing
              written notice. This will come into effect upon the expiration of the current duration of
              the Merchant’s agreement to the Terms, and the Merchant may carry out the remainder
              of the period abiding by the prior Terms. By renewing the subscription, the Merchant
              assumes agreement to the updated Terms. You may refer to the “Last Updated” notice
              at the top of this agreement should changes occur.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Merchant’s Registration Details</h3>
            <p className="leading-7">
              Merchants must also provide and maintain accurate, current, and complete
              registration information. You are responsible for safeguarding Your account credentials
              and preventing unauthorised access. Any activity on the account, whether authorised
              or not, is the Merchant’s responsibility.
            </p>
            <h3 className="text-lg font-semibold mt-4">iii) Disputes and Jurisdiction</h3>
            <p className="leading-7">
              Any disputes regarding the Services and the Agreements shall be governed by the
              applicable legislation of England and Wales and handled through arbitration, with no
              jury trials or class actions allowed. Arbitration shall be final and binding, with the
              Parties covering their own costs unless otherwise agreed. If in any case arbitration is
              not legal, disputes shall be resolved in the British court of law. Amaanah retains the
              right to seek court intervention for the protection of Our Intellectual Property or
              collection of outstanding payments.
            </p>
            <h3 className="text-lg font-semibold mt-4">iv) Unenforceable Provisions</h3>
            <p className="leading-7">
              If any provision is unenforceable, it shall be waived without affecting the rest of this
              agreement. Amaanah may assign Our rights or use subcontractors, but the Merchant
              must not assign their rights without consent. This agreement supersedes all prior
              communications and is the entire understanding between the Parties. The Terms are
              agreed in the English language unless required otherwise by law.
            </p>
            <h3 className="text-lg font-semibold mt-4">v) Binding Term of the Document</h3>
            <p className="leading-7">
              This agreement begins on the Agreement Created Date and lasts for the initial term
              specified on the License Contract. It automatically renews for the same duration unless
              either the Merchant provides written notice 12 months’ prior to the end of the term, or
              Amaanah terminates the Agreement with 30 days’ notice. Services are subscription-based, and merchants cannot terminate them prematurely.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Fees and Payments</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Amaanah shall charge the fees as per the Merchant’s License Contract from the
                Effective Date.</li>
              <li>Fees cover the licensing of software, rental of hardware, and any other Services</li>
              <li>Payments are due on time, and late payments may lead to the suspension of the
                Services.</li>
              <li>Merchants are responsible for all applicable taxes, and Amaanah is not liable for
                any tax-related obligations.</li>
            </ul>
            <p className="leading-7">
              If Amaanah modifies the License Contract to the Merchant’s dissatisfaction, the
              Merchant may then notify Amaanah of their cancellation request and end their use of
              the Services.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">
              Licensing, Intellectual Property, and Data Access
            </h2>
            <h3 className="text-lg font-semibold mt-4">i) Intellectual Property of Amaanah</h3>
            <p className="leading-7">
              The Content of the Services, excluding User Content, is the intellectual property of
              Amaanah or Our respective licensors, and is protected by British and international
              patent, trademark, and copyright laws, and all rights to Amaanah Services, such
              Content, and such software are expressly reserved by Us. All trademarks, registered
              trademarks, product names, company names, or logos mentioned in Amaanah
              Services are the property of their respective owners, and such mention does not
              constitute endorsement.
            </p>
            <p className="leading-7">
              The Merchant also assigns all intellectual property rights to the feedback given to
              Amaanah immediately upon communication of such feedback to Amaanah or Our
              representatives.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Licensing of the Services to the Merchant</h3>
            <p className="leading-7">
              Amaanah hereby grants the Merchant a limited, non-exclusive, non-transferable, and
              revocable license to use Our services in compliance with the Terms. This license does
              not grant ownership of Our intellectual property, and We may revoke this license at any
              time upon refunding the amount paid for the remaining subscription term. The
              Merchant must use the Services legally without misusing or modifying the Contents in
              any unauthorised manner.
            </p>
            <h3 className="text-lg font-semibold mt-4">iii) Licensing of Merchant Content to Us</h3>
            <p className="leading-7">
              The Merchant hereby grants Amaanah a non-exclusive, transferable, royalty-free
              license to use the Merchant’s content as necessary for providing the Services. The
              Merchant is responsible for ensuring the legality and accuracy of the content and must
              not upload anything that violates the laws of England and Wales, infringes intellectual
              property rights, or is inappropriate.
            </p>
            <h3 className="text-lg font-semibold mt-4">iv) Licensing of Merchant’s Trademark for Marketing Purposes</h3>
            <p className="leading-7">
              The Merchant hereby grants Amaanah a non-exclusive, royalty-free right and license to
              use and display the Merchant’s branding artifacts on the Sites or to otherwise publicly
              identify the Merchant as a customer of Amaanah.
            </p>
            <h3 className="text-lg font-semibold mt-4">v) Third Party Access to Data</h3>
            <p className="leading-7">
              Should the Merchant authorise third parties to access the Merchant’s User Content
              through the Services, the Merchant should give their agreement to Our provision of the
              User Content and that We are not liable or responsible for the use or misuse of any
              such content, or data loss, by the third party.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Usage Restrictions</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>The Users may not interfere or attempt to interfere with the proper performance
                of the Services.</li>
              <li>The Merchant may not misrepresent their own identity.</li>
              <li>The Users may not use the Services for illegal, harmful, or unauthorised
                activities. This includes copying, modifying, reselling, or exploiting the Services
                without permission.</li>
              <li>The Users must not attempt unauthorised access or misuse data.</li>
              <li>All User Content shared must comply with applicable laws.</li>
            </ul>
            <p className="leading-7">
              Any third parties involved by the Merchant must follow the usage restrictions provided
              by Amaanah as originally expected of the Merchant.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">
              Installation and Hardware Performance
            </h2>
            <h3 className="text-lg font-semibold mt-4">i) Initial Support</h3>
            <p className="leading-7">
              Professional services, such as on-site installation and support, are chargeable
              services and Amaanah does not allow the use of third-party providers of such
              services. See the charges below:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Delivery and Redelivery - £20.00</li>
              <li>On-Site Installation – from £150.00</li>
              <li>Menu Insertion – from £99.00</li>
              <li>Data Transfer – From £49.00</li>
              <li>Training – Free of charge for the first three sessions and chargeable there
                onwards</li>
              <li>Website/Domain Hosting Management - £19.00/month</li>
            </ul>
            <h3 className="text-lg font-semibold mt-4">ii) Data Transfer</h3>
            <p className="leading-7">
              If the Merchant opts for the chargeable data transfer service to migrate the
              Merchant’s current User Content onto Our software, they hereby confirm that:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Any and all data is their own, and they have full ownership and rights to do
                with the data as they please,</li>
              <li>Amaanah will not be held liable for any disputes between the Merchant and
                the previous service provider, and it is the sole responsibility of the
                Merchant,</li>
              <li>And the Merchant has reliable measures and backups in place in case of any
                incompatibility of the data provided with the operating systems of the
                Amaanah platform; there is a possibility that although data may be stored on
                the system, it may not be visible or readable on the interface.</li>
            </ul>
            <p className="leading-7">
              This service is at the full discretion of Amaanah and there is no guarantee that
              the Merchant will be able to migrate their data whether due to size,
              incompatibility or otherwise. Furthermore, Amaanah will not accept liability for
              any data loss, data corruption, or hardware damage during this process, and it is
              the responsibility of the Merchant to mitigate this risk.
            </p>
            <p className="leading-7">
              The Merchant also agrees that they do not have ownership rights to the data or
              User Content created on the Amaanah software and that this data will not be
              shared or migrated upon termination due to privacy concerns. This data will be
              safely stored on Our servers without any tampering, abiding by GDPR security
              policy.
            </p>
            <h3 className="text-lg font-semibold mt-4">iii) Device Compatibility</h3>
            <p className="leading-7">
              Amaanah does not guarantee compatibility with all devices and is not
              responsible for issues caused by third-party hardware. Approved hardware may
              be required for optimum performance.
            </p>
            <p className="leading-7">
              However, an initial hardware inspection is offered, in which case either:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Amaanah can clearly identify device incompatibility and advise the Merchant
                to replace their existing or unused third-party equipment or</li>
              <li>Amaanah can confirm that it is possible to use the existing or unused third-party hardware with no guarantee or liability regarding the outcome; the
                software may or may not run, or may cause further damage to the
                equipment.</li>
            </ul>
            <p className="leading-7">
              Amaanah will also not accept liability for any hardware issues arising after the
              Merchant has been fully integrated with Our Services for a period and have
              experienced the performance of the system; We are not liable to any claims of
              wear and tear, or depreciation caused by the running of Our software.
            </p>
            <p className="leading-7">
              Furthermore, under no circumstances will We accept liability for injury resulting
              from any Users’ use of the equipment.
            </p>
            <h3 className="text-lg font-semibold mt-4">iv) Approved Hardware</h3>
            <p className="leading-7">
              The approved hardware may be purchased according to our recommendation or
              purchased through Us. If you source your hardware following our
              recommendation; all disputes and liabilities are to be resolved between the
              Merchant and the third-party.
            </p>
            <p className="leading-7">
              Amaanah will only accept liability over hardware purchased through us or
              financed by Us, which comes with the standard product warranty.
            </p>
            <p className="leading-7">
              This warranty will not cover accidental damage, cosmetic damage or damage
              from the use of unsuitable consumables e.g. paper rolls for the printer. The
              replacement will be delivered at the earliest and will be of equal or greater
              specification, but it may not be new.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Maintenance and Updates</h2>
            <p className="leading-7">
              Amaanah may conduct scheduled or unscheduled maintenance, updates, or patches
              to improve Our services. These updates may cause temporary disruptions, but the
              Merchant must ensure that they integrate any required updates to continue using the
              Services. We are not obligated to support outdated versions of Our software.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Communications</h2>
            <p className="leading-7">
              Amaanah may communicate with the Merchant through email, phone, account
              dashboard notification, or website postings. The Merchant must keep their contact
              information up to date and check for notices. The Merchant hereby agrees that any
              ideas or submissions shared with Us may be used without compensation or
              acknowledgement.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Social Media Areas</h2>
            <p className="leading-7">
              The Services may include forums and other Social Media Areas. If such a service is
              provided, the Merchant may use it solely at their own risk, and any content uploaded to
              these public Areas will be considered non-confidential. The Merchant must ensure that
              their content is lawful, non-offensive, and that it is not in violation of intellectual
              property rights. Amaanah reserves the right to monitor and interfere with any content
              that breaches Our policies. The Merchant is also prohibited from sharing misleading or
              harmful information. Any violation of these Terms may result in termination of access to
              the Services.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Gift Card Services</h2>
            <p className="leading-7">
              Amaanah provides a gift card service for businesses to issue and manage gift cards.
              However:
            </p>
            <ul className="list-disc list-inside space-y-1">
              <li>The Merchant is responsible for compliance with legal and tax regulations.</li>
              <li>Amaanah is not liable for lost, stolen, or unauthorised use of the gift cards.</li>
              <li>The Merchant must properly record transactions and maintain gift card
                balances; the Merchant is solely responsible for funding and managing the
                program.</li>
              <li>Customer disputes regarding the program must be handled and resolved by the
                Merchant.</li>
              <li>Amaanah does not guarantee the security or performance of the services.</li>
              <li>Financial losses related to gift cards are the responsibility of the Merchant.</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Payment Processing</h2>
            <h3 className="text-lg font-semibold mt-4">i) Third-Party Providers</h3>
            <p className="leading-7">
              Amaanah enables the Merchant to receive payments through third-party
              payment processing services. However, the Merchant must comply with the
              terms set by these third-party providers and is responsible for providing accurate
              payment information. Amaanah does not process payments directly, and We are
              not liable for any issues related to such transactions. Additionally, the Merchant
              may be required to sign agreements with either third-party payment processors
              to use the Services.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Affiliate Provider</h3>
            <p className="leading-7">
              Payment Process is Our affiliate provider of payment processing services and
              both their Terms and Conditions and Privacy Policy can be found on
              www.paymentprocess.co.uk. Additionally, if You so choose this option, You will
              be provided with Terms of Use documentation along with Your rental agreement.
              To use these services, You must ensure Your full understanding and agreement
              to the relevant terms outlined by the affiliate.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Third-Party Material</h2>
            <h3 className="text-lg font-semibold mt-4">i) Links</h3>
            <p className="leading-7">
              The Services may consist of links to third-party websites and content. We are not
              responsible for the content, services, or transactions thereof, nor do We endorse them.
              When using third-party services, the Merchant must review the third-party's terms and
              conditions. The provider of each third-party service is solely responsible for their
              content, services, or transactions, as well as any warranties or support offered.
              Amaanah is not a party to any license agreement between the Merchant and the third-
              party service provider, but only a third-party beneficiary with the right to enforce the
              terms of the third-party service agreement.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Advertisements and Promotions</h3>
            <p className="leading-7">
              Amaanah may feature third-party advertisements and promotions, but We are not
              responsible for any interactions, terms, or issues arising from the Merchant and the
              third-party. Any dealings are solely between the Merchant and the advertiser.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Privacy and Security</h2>
            <h3 className="text-lg font-semibold mt-4">i) Data Processing by Amaanah</h3>
            <p className="leading-7">
              For detailed information on how Amaanah collects and stores the data of the users of
              Our Sites and Services, please refer to Our Privacy Policy on Our website. By using the
              Services, the Merchant agrees to Our use of their personal details in accordance with
              Our Privacy Policy, the GDPR, and the applicable legislation of the European Economic
              Area.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Data Processing by the Merchant</h3>
            <p className="leading-7">
              The Merchant must comply with all applicable data privacy laws and Our Privacy Policy
              when handling User data. You are required to implement appropriate security
              measures to protect the personal information of all Users. Additionally, the Merchant
              must assist Us in responding to privacy-related concerns and requests and notify Users
              of any data breaches or security risks. Amaanah reserves the right to monitor the
              Merchant’s compliance with these requirements.
            </p>
            <h3 className="text-lg font-semibold mt-4">iii) Disclosure of Confidential Information</h3>
            <p className="leading-7">
              Confidential Information is defined as part of the definitions set out on page 2 and does
              not include information that is already known or available to the public.
            </p>
            <p className="leading-7">
              The receiving party must protect and shall not disclose such information, except:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>To their representatives who are legally and ethically bound to confidentiality,</li>
              <li>When required by law (with prior notice, if permitted) or,</li>
              <li>As allowed by the Privacy Policy.</li>
            </ul>
            <p className="leading-7">
              Consequently, the receiving party remains responsible for any breaches by their
              representatives.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Software Warranty Disclaimer</h2>
            <p className="leading-7">
              We provide Our software without warranties, including those for accuracy, reliability, or
              uninterrupted access. Merchants assume the risk of service disruptions and should
              have backup systems for business continuity. Amaanah does not guarantee Our
              Services or third-party integrations are free from errors, viruses, or interruptions.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Liability and Indemnity</h2>
            <h3 className="text-lg font-semibold mt-4">i) Damages from Use of the Services</h3>
            <p className="leading-7">
              The Merchant cannot hold Amaanah or Our partners responsible for any claims or
              damages related to their use of Our Services or third-party services. We are not liable
              for any customer disputes related to reservations, online orders, or gift cards. These are
              the sole responsibility of the Merchant.
            </p>
            <p className="leading-7">
              Amaanah and Our affiliates are not responsible for any direct, indirect, or
              consequential damages, including loss of data, profits, or goodwill, resulting from
              service use, errors, interruptions, or security breaches. In any case, Our total liability is
              limited to the amount the Merchant paid for the Services in the three months prior to
              the claim.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Force Majeure</h3>
            <p className="leading-7">
              Amaanah will not be liable for any failure or delay resulting from any condition beyond
              Our reasonable control, including but not limited to governmental action or acts of
              terrorism, earthquake, fire, pandemic, flood, or other acts of God, labour conditions,
              power failures, and internet disturbances.
            </p>
            <h3 className="text-lg font-semibold mt-4">iii) Indemnification</h3>
            <p className="leading-7">
              The Merchant must comply with local laws and indemnify Amaanah for any legal issues
              arising from non-compliance. The Merchant must also indemnify Us against any claims
              related to their use of the Services, including those involving intellectual property
              disputes. Some jurisdictions may limit liability disclaimers, but Amaanah will seek the
              maximum protection allowed by law.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Default</h2>
            <p className="leading-7">
              In the case of the Merchant defaulting, Amaanah may terminate the agreement and
              require immediate payment of fees, including those payable for software licenses and
              rented hardware. If the Merchant is also subscribed to a hardware plan, Amaanah may
              remotely disable the devices provided within this plan.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Other Charges and Penalties</h2>
            <h3 className="text-lg font-semibold mt-4">i) Failed Deliveries</h3>
            <p className="leading-7">
              The Merchant must be available to collect any purchases and the charge for
              failed deliveries shall be £30.00.
            </p>
            <h3 className="text-lg font-semibold mt-4">ii) Maintenance Visits</h3>
            <p className="leading-7">
              Remote customer service is free of charge, but please note that beyond three
              months of the Merchant’s custom (upon the installation of the system), in-person visits for maintenance and repair shall be charged at £50.00 per visit.
            </p>
            <h3 className="text-lg font-semibold mt-4">iii) Early Termination</h3>
            <p className="leading-7">
              The minimum period for the contract is 36 months unless otherwise agreed, and
              it may be terminated with 12 months’ prior notice without charge, except for the
              payment of any arrears. If the Agreement is terminated for any reason before
              expiry of the minimum period, the Merchant will be liable to pay the remaining
              fees for the minimum period, along with an early termination administration
              charge of £50.00.
            </p>
            <h3 className="text-lg font-semibold mt-4">iv) Late Payments</h3>
            <p className="leading-7">
              The Merchant agrees to pay the dues on the agreed date monthly and late
              payments shall be penalised with an additional fee of £25.00 for each month
              unpaid.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-xl font-semibold mb-2">Termination</h2>
            <p className="leading-7">
              Once the subscription is terminated, whether at the agreed date or through writing at an
              earlier date, Merchant Content will be removed from Our Services, except for materials
              posted on Our website or social media, which may remain. Amaanah may keep an
              archival copy of Merchant Content for internal purposes abiding by the privacy
              regulations of the GDPR.
            </p>
          </section>
          <p className="text-muted-foreground text-sm text-right mt-6">Amaanah © 2025</p>
        </CardContent>
      </Card>
    </TabsContent>
  );
}

export default LicenseTerms;